// Auto-generated by OpenLane
module ripple_adder_wrapper(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input enable,
  input[7:0] a,
  input[7:0] b,
  input cin,
  output[7:0] sum,
  output cout
);
endmodule
