/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 16.0.6 -fPIC -O3) */

module ripple_adder_wrapper(clk, reset, enable, a, b, cin, sum, cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input cin;
  wire cin;
  wire cin_r;
  input clk;
  wire clk;
  output cout;
  wire cout;
  input enable;
  wire enable;
  input reset;
  wire reset;
  output [7:0] sum;
  wire [7:0] sum;
  wire \u_rip.fa0.a ;
  wire \u_rip.fa0.b ;
  wire \u_rip.gen_fa[1].fa.a ;
  wire \u_rip.gen_fa[1].fa.b ;
  wire \u_rip.gen_fa[2].fa.a ;
  wire \u_rip.gen_fa[2].fa.b ;
  wire \u_rip.gen_fa[3].fa.a ;
  wire \u_rip.gen_fa[3].fa.b ;
  wire \u_rip.gen_fa[4].fa.a ;
  wire \u_rip.gen_fa[4].fa.b ;
  wire \u_rip.gen_fa[5].fa.a ;
  wire \u_rip.gen_fa[5].fa.b ;
  wire \u_rip.gen_fa[6].fa.a ;
  wire \u_rip.gen_fa[6].fa.b ;
  wire \u_rip.gen_fa[7].fa.a ;
  wire \u_rip.gen_fa[7].fa.b ;
  sky130_fd_sc_hd__or2_2 _079_ (
    .A(cin_r),
    .B(\u_rip.fa0.a ),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand2_2 _080_ (
    .A(cin_r),
    .B(\u_rip.fa0.a ),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_2 _081_ (
    .A1(_048_),
    .A2(_049_),
    .B1(\u_rip.fa0.b ),
    .Y(_050_)
  );
  sky130_fd_sc_hd__and3_2 _082_ (
    .A(\u_rip.fa0.b ),
    .B(_048_),
    .C(_049_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nor3_2 _083_ (
    .A(reset),
    .B(_050_),
    .C(_051_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a21boi_2 _084_ (
    .A1(\u_rip.fa0.b ),
    .A2(_048_),
    .B1_N(_049_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2b_2 _085_ (
    .A_N(_052_),
    .B(\u_rip.gen_fa[1].fa.a ),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xnor2_2 _086_ (
    .A(\u_rip.gen_fa[1].fa.a ),
    .B(_052_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__or2_2 _087_ (
    .A(\u_rip.gen_fa[1].fa.b ),
    .B(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand2_2 _088_ (
    .A(\u_rip.gen_fa[1].fa.b ),
    .B(_054_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__and3b_2 _089_ (
    .A_N(reset),
    .B(_055_),
    .C(_056_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand3b_2 _090_ (
    .A_N(\u_rip.gen_fa[2].fa.a ),
    .B(_053_),
    .C(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a21bo_2 _091_ (
    .A1(_053_),
    .A2(_056_),
    .B1_N(\u_rip.gen_fa[2].fa.a ),
    .X(_058_)
  );
  sky130_fd_sc_hd__and2_2 _092_ (
    .A(_057_),
    .B(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__a21oi_2 _093_ (
    .A1(\u_rip.gen_fa[2].fa.b ),
    .A2(_059_),
    .B1(reset),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21a_2 _094_ (
    .A1(\u_rip.gen_fa[2].fa.b ),
    .A2(_059_),
    .B1(_060_),
    .X(_002_)
  );
  sky130_fd_sc_hd__a21bo_2 _095_ (
    .A1(\u_rip.gen_fa[2].fa.b ),
    .A2(_057_),
    .B1_N(_058_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nand2_2 _096_ (
    .A(\u_rip.gen_fa[3].fa.a ),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xor2_2 _097_ (
    .A(\u_rip.gen_fa[3].fa.a ),
    .B(_061_),
    .X(_063_)
  );
  sky130_fd_sc_hd__or2_2 _098_ (
    .A(\u_rip.gen_fa[3].fa.b ),
    .B(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nand2_2 _099_ (
    .A(\u_rip.gen_fa[3].fa.b ),
    .B(_063_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__and3b_2 _100_ (
    .A_N(reset),
    .B(_064_),
    .C(_065_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand3b_2 _101_ (
    .A_N(\u_rip.gen_fa[4].fa.a ),
    .B(_062_),
    .C(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a21bo_2 _102_ (
    .A1(_062_),
    .A2(_065_),
    .B1_N(\u_rip.gen_fa[4].fa.a ),
    .X(_067_)
  );
  sky130_fd_sc_hd__and2_2 _103_ (
    .A(_066_),
    .B(_067_),
    .X(_068_)
  );
  sky130_fd_sc_hd__a21oi_2 _104_ (
    .A1(\u_rip.gen_fa[4].fa.b ),
    .A2(_068_),
    .B1(reset),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o21a_2 _105_ (
    .A1(\u_rip.gen_fa[4].fa.b ),
    .A2(_068_),
    .B1(_069_),
    .X(_004_)
  );
  sky130_fd_sc_hd__a21bo_2 _106_ (
    .A1(\u_rip.gen_fa[4].fa.b ),
    .A2(_066_),
    .B1_N(_067_),
    .X(_070_)
  );
  sky130_fd_sc_hd__nand2_2 _107_ (
    .A(\u_rip.gen_fa[5].fa.a ),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xor2_2 _108_ (
    .A(\u_rip.gen_fa[5].fa.a ),
    .B(_070_),
    .X(_072_)
  );
  sky130_fd_sc_hd__or2_2 _109_ (
    .A(\u_rip.gen_fa[5].fa.b ),
    .B(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand2_2 _110_ (
    .A(\u_rip.gen_fa[5].fa.b ),
    .B(_072_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__and3b_2 _111_ (
    .A_N(reset),
    .B(_073_),
    .C(_074_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand3b_2 _112_ (
    .A_N(\u_rip.gen_fa[6].fa.a ),
    .B(_071_),
    .C(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21bo_2 _113_ (
    .A1(_071_),
    .A2(_074_),
    .B1_N(\u_rip.gen_fa[6].fa.a ),
    .X(_076_)
  );
  sky130_fd_sc_hd__and2_2 _114_ (
    .A(_075_),
    .B(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__a21oi_2 _115_ (
    .A1(\u_rip.gen_fa[6].fa.b ),
    .A2(_077_),
    .B1(reset),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o21a_2 _116_ (
    .A1(\u_rip.gen_fa[6].fa.b ),
    .A2(_077_),
    .B1(_078_),
    .X(_006_)
  );
  sky130_fd_sc_hd__a21boi_2 _117_ (
    .A1(\u_rip.gen_fa[6].fa.b ),
    .A2(_075_),
    .B1_N(_076_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2b_2 _118_ (
    .A_N(_026_),
    .B(\u_rip.gen_fa[7].fa.a ),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_2 _119_ (
    .A(\u_rip.gen_fa[7].fa.a ),
    .B(_026_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__or2_2 _120_ (
    .A(\u_rip.gen_fa[7].fa.b ),
    .B(_028_),
    .X(_029_)
  );
  sky130_fd_sc_hd__nand2_2 _121_ (
    .A(\u_rip.gen_fa[7].fa.b ),
    .B(_028_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__and3b_2 _122_ (
    .A_N(reset),
    .B(_029_),
    .C(_030_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _123_ (
    .A0(\u_rip.fa0.a ),
    .A1(a[0]),
    .S(enable),
    .X(_031_)
  );
  sky130_fd_sc_hd__and2b_2 _124_ (
    .A_N(reset),
    .B(_031_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _125_ (
    .A0(\u_rip.gen_fa[1].fa.a ),
    .A1(a[1]),
    .S(enable),
    .X(_032_)
  );
  sky130_fd_sc_hd__and2b_2 _126_ (
    .A_N(reset),
    .B(_032_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _127_ (
    .A0(\u_rip.gen_fa[2].fa.a ),
    .A1(a[2]),
    .S(enable),
    .X(_033_)
  );
  sky130_fd_sc_hd__and2b_2 _128_ (
    .A_N(reset),
    .B(_033_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _129_ (
    .A0(\u_rip.gen_fa[3].fa.a ),
    .A1(a[3]),
    .S(enable),
    .X(_034_)
  );
  sky130_fd_sc_hd__and2b_2 _130_ (
    .A_N(reset),
    .B(_034_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _131_ (
    .A0(\u_rip.gen_fa[4].fa.a ),
    .A1(a[4]),
    .S(enable),
    .X(_035_)
  );
  sky130_fd_sc_hd__and2b_2 _132_ (
    .A_N(reset),
    .B(_035_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _133_ (
    .A0(\u_rip.gen_fa[5].fa.a ),
    .A1(a[5]),
    .S(enable),
    .X(_036_)
  );
  sky130_fd_sc_hd__and2b_2 _134_ (
    .A_N(reset),
    .B(_036_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(\u_rip.gen_fa[6].fa.a ),
    .A1(a[6]),
    .S(enable),
    .X(_037_)
  );
  sky130_fd_sc_hd__and2b_2 _136_ (
    .A_N(reset),
    .B(_037_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _137_ (
    .A0(\u_rip.gen_fa[7].fa.a ),
    .A1(a[7]),
    .S(enable),
    .X(_038_)
  );
  sky130_fd_sc_hd__and2b_2 _138_ (
    .A_N(reset),
    .B(_038_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _139_ (
    .A0(\u_rip.fa0.b ),
    .A1(b[0]),
    .S(enable),
    .X(_039_)
  );
  sky130_fd_sc_hd__and2b_2 _140_ (
    .A_N(reset),
    .B(_039_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(\u_rip.gen_fa[1].fa.b ),
    .A1(b[1]),
    .S(enable),
    .X(_040_)
  );
  sky130_fd_sc_hd__and2b_2 _142_ (
    .A_N(reset),
    .B(_040_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(\u_rip.gen_fa[2].fa.b ),
    .A1(b[2]),
    .S(enable),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2b_2 _144_ (
    .A_N(reset),
    .B(_041_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(\u_rip.gen_fa[3].fa.b ),
    .A1(b[3]),
    .S(enable),
    .X(_042_)
  );
  sky130_fd_sc_hd__and2b_2 _146_ (
    .A_N(reset),
    .B(_042_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(\u_rip.gen_fa[4].fa.b ),
    .A1(b[4]),
    .S(enable),
    .X(_043_)
  );
  sky130_fd_sc_hd__and2b_2 _148_ (
    .A_N(reset),
    .B(_043_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _149_ (
    .A0(\u_rip.gen_fa[5].fa.b ),
    .A1(b[5]),
    .S(enable),
    .X(_044_)
  );
  sky130_fd_sc_hd__and2b_2 _150_ (
    .A_N(reset),
    .B(_044_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _151_ (
    .A0(\u_rip.gen_fa[6].fa.b ),
    .A1(b[6]),
    .S(enable),
    .X(_045_)
  );
  sky130_fd_sc_hd__and2b_2 _152_ (
    .A_N(reset),
    .B(_045_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _153_ (
    .A0(\u_rip.gen_fa[7].fa.b ),
    .A1(b[7]),
    .S(enable),
    .X(_046_)
  );
  sky130_fd_sc_hd__and2b_2 _154_ (
    .A_N(reset),
    .B(_046_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _155_ (
    .A0(cin_r),
    .A1(cin),
    .S(enable),
    .X(_047_)
  );
  sky130_fd_sc_hd__and2b_2 _156_ (
    .A_N(reset),
    .B(_047_),
    .X(_024_)
  );
  sky130_fd_sc_hd__a21oi_2 _157_ (
    .A1(_027_),
    .A2(_030_),
    .B1(reset),
    .Y(_025_)
  );
  sky130_fd_sc_hd__dfxtp_2 _158_ (
    .CLK(clk),
    .D(_000_),
    .Q(sum[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _159_ (
    .CLK(clk),
    .D(_001_),
    .Q(sum[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _160_ (
    .CLK(clk),
    .D(_002_),
    .Q(sum[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _161_ (
    .CLK(clk),
    .D(_003_),
    .Q(sum[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _162_ (
    .CLK(clk),
    .D(_004_),
    .Q(sum[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _163_ (
    .CLK(clk),
    .D(_005_),
    .Q(sum[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _164_ (
    .CLK(clk),
    .D(_006_),
    .Q(sum[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _165_ (
    .CLK(clk),
    .D(_007_),
    .Q(sum[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _166_ (
    .CLK(clk),
    .D(_008_),
    .Q(\u_rip.fa0.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _167_ (
    .CLK(clk),
    .D(_009_),
    .Q(\u_rip.gen_fa[1].fa.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _168_ (
    .CLK(clk),
    .D(_010_),
    .Q(\u_rip.gen_fa[2].fa.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _169_ (
    .CLK(clk),
    .D(_011_),
    .Q(\u_rip.gen_fa[3].fa.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _170_ (
    .CLK(clk),
    .D(_012_),
    .Q(\u_rip.gen_fa[4].fa.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _171_ (
    .CLK(clk),
    .D(_013_),
    .Q(\u_rip.gen_fa[5].fa.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _172_ (
    .CLK(clk),
    .D(_014_),
    .Q(\u_rip.gen_fa[6].fa.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _173_ (
    .CLK(clk),
    .D(_015_),
    .Q(\u_rip.gen_fa[7].fa.a )
  );
  sky130_fd_sc_hd__dfxtp_2 _174_ (
    .CLK(clk),
    .D(_016_),
    .Q(\u_rip.fa0.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _175_ (
    .CLK(clk),
    .D(_017_),
    .Q(\u_rip.gen_fa[1].fa.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _176_ (
    .CLK(clk),
    .D(_018_),
    .Q(\u_rip.gen_fa[2].fa.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _177_ (
    .CLK(clk),
    .D(_019_),
    .Q(\u_rip.gen_fa[3].fa.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _178_ (
    .CLK(clk),
    .D(_020_),
    .Q(\u_rip.gen_fa[4].fa.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _179_ (
    .CLK(clk),
    .D(_021_),
    .Q(\u_rip.gen_fa[5].fa.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _180_ (
    .CLK(clk),
    .D(_022_),
    .Q(\u_rip.gen_fa[6].fa.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _181_ (
    .CLK(clk),
    .D(_023_),
    .Q(\u_rip.gen_fa[7].fa.b )
  );
  sky130_fd_sc_hd__dfxtp_2 _182_ (
    .CLK(clk),
    .D(_024_),
    .Q(cin_r)
  );
  sky130_fd_sc_hd__dfxtp_2 _183_ (
    .CLK(clk),
    .D(_025_),
    .Q(cout)
  );
endmodule
