// Auto-generated by OpenLane
module reversible_wrapper(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input enable,
  input[7:0] a,
  input[7:0] b,
  input[7:0] anc,
  input cin,
  output[7:0] sum,
  output cout,
  output[7:0] g_a,
  output[7:0] g_ab
);
endmodule
