#!/usr/bin/env python3
"""
parse_power.py - Power report parser for OpenROAD tabular format

This script parses power reports generated by OpenROAD's report_power command
and computes normalized energy metrics for comparing adder designs:
  - Energy per addition operation
  - Energy per sum bit
  - Energy per input toggle
  - Clock vs logic energy split
  - Overhead due to reversible garbage/ancilla nets

Usage:
    python3 parse_power.py <power_report_file> [options]
    python3 parse_power.py --compare <report1> <report2> [<report3>]

Options:
    --num-additions N     Number of addition operations in simulation (default: 256)
    --num-sum-bits N      Number of sum bits (default: 8)
    --clock-period NS     Clock period in nanoseconds (default: 25)
    --compare             Compare multiple power reports
    --json                Output results as JSON
    --csv                 Output results as CSV

Example:
    python3 parse_power.py power_reports/reversible_wrapper_power.rpt --num-additions 256
    python3 parse_power.py --compare reversible_power.rpt ripple_power.rpt carry_select_power.rpt
"""

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class PowerMetrics:
    """Container for parsed power metrics."""
    design_name: str
    total_power_mw: float
    internal_power_mw: float
    switching_power_mw: float
    leakage_power_mw: float
    clock_power_mw: float
    logic_power_mw: float
    # Additional metrics
    num_cells: int = 0
    num_nets: int = 0
    annotated_pins: int = 0
    total_pins: int = 0


@dataclass
class NormalizedMetrics:
    """Container for normalized energy metrics."""
    energy_per_addition_pj: float
    energy_per_sum_bit_pj: float
    energy_per_toggle_pj: float
    clock_energy_fraction: float
    logic_energy_fraction: float
    leakage_energy_fraction: float
    annotation_coverage: float  # Fraction of pins with activity annotation


def parse_openroad_power_report(filepath: str) -> PowerMetrics:
    """
    Parse OpenROAD power report in tabular format.
    
    OpenROAD report_power output format example:
    
    Group                  Internal  Switching    Leakage      Total
                             Power      Power      Power      Power (Watts)
    ----------------------------------------------------------------
    Sequential             1.23e-04   2.34e-05   3.45e-08   1.47e-04
    Combinational          2.34e-04   3.45e-05   4.56e-08   2.69e-04
    Clock                  5.67e-05   6.78e-06   7.89e-09   6.35e-05
    Macro                  0.00e+00   0.00e+00   0.00e+00   0.00e+00
    Pad                    0.00e+00   0.00e+00   0.00e+00   0.00e+00
    ----------------------------------------------------------------
    Total                  4.14e-04   6.46e-05   1.28e-07   4.79e-04
    
    Also handles formats like:
    - "Annotated X pin activities" 
    - Power in various units (W, mW, uW, nW)
    """
    content = Path(filepath).read_text()
    
    # Extract design name from filename
    design_name = Path(filepath).stem.replace("_power", "")
    
    # Initialize metrics
    metrics = PowerMetrics(
        design_name=design_name,
        total_power_mw=0.0,
        internal_power_mw=0.0,
        switching_power_mw=0.0,
        leakage_power_mw=0.0,
        clock_power_mw=0.0,
        logic_power_mw=0.0,
    )
    
    # Parse annotation coverage
    # Pattern: "Annotated X pin activities" or "Annotated X out of Y pins"
    annotation_patterns = [
        r"Annotated\s+(\d+)\s+pin\s+activit",
        r"Annotated\s+(\d+)\s+out\s+of\s+(\d+)\s+pins",
        r"(\d+)\s+of\s+(\d+)\s+pins\s+annotated",
    ]
    for pattern in annotation_patterns:
        match = re.search(pattern, content, re.IGNORECASE)
        if match:
            metrics.annotated_pins = int(match.group(1))
            if len(match.groups()) > 1:
                metrics.total_pins = int(match.group(2))
            break
    
    # Parse power table rows
    # Match patterns like:
    # Sequential             1.23e-04   2.34e-05   3.45e-08   1.47e-04
    # Total                  4.14e-04   6.46e-05   1.28e-07   4.79e-04
    
    power_row_pattern = r"(\w+)\s+([\d.eE+-]+)\s+([\d.eE+-]+)\s+([\d.eE+-]+)\s+([\d.eE+-]+)"
    
    internal_sum = 0.0
    switching_sum = 0.0
    leakage_sum = 0.0
    total_sum = 0.0
    clock_power = 0.0
    
    for match in re.finditer(power_row_pattern, content):
        group_name = match.group(1).lower()
        internal = float(match.group(2))
        switching = float(match.group(3))
        leakage = float(match.group(4))
        total = float(match.group(5))
        
        if group_name == "total":
            internal_sum = internal
            switching_sum = switching
            leakage_sum = leakage
            total_sum = total
        elif group_name == "clock":
            clock_power = total
    
    # Convert Watts to milliwatts
    metrics.internal_power_mw = internal_sum * 1000
    metrics.switching_power_mw = switching_sum * 1000
    metrics.leakage_power_mw = leakage_sum * 1000
    metrics.total_power_mw = total_sum * 1000
    metrics.clock_power_mw = clock_power * 1000
    
    # Logic power = total - clock - leakage
    metrics.logic_power_mw = max(0, metrics.total_power_mw - metrics.clock_power_mw - metrics.leakage_power_mw)
    
    # Alternative parsing if standard format wasn't found
    if metrics.total_power_mw == 0:
        # Try alternative formats
        alt_patterns = [
            (r"Total\s+Power[:\s]+([\d.eE+-]+)\s*(m?W)", "total"),
            (r"Internal\s+Power[:\s]+([\d.eE+-]+)\s*(m?W)", "internal"),
            (r"Switching\s+Power[:\s]+([\d.eE+-]+)\s*(m?W)", "switching"),
            (r"Leakage\s+Power[:\s]+([\d.eE+-]+)\s*(m?W)", "leakage"),
            (r"Clock\s+Power[:\s]+([\d.eE+-]+)\s*(m?W)", "clock"),
        ]
        
        for pattern, attr in alt_patterns:
            match = re.search(pattern, content, re.IGNORECASE)
            if match:
                value = float(match.group(1))
                unit = match.group(2).lower() if len(match.groups()) > 1 else "w"
                
                # Convert to milliwatts
                if unit == "w":
                    value *= 1000
                elif unit == "uw" or unit == "μw":
                    value /= 1000
                elif unit == "nw":
                    value /= 1e6
                # mW stays as is
                
                setattr(metrics, f"{attr}_power_mw", value)
    
    return metrics


def compute_normalized_metrics(
    power_metrics: PowerMetrics,
    num_additions: int = 256,
    num_sum_bits: int = 8,
    clock_period_ns: float = 25.0,
) -> NormalizedMetrics:
    """
    Compute normalized energy metrics from power measurements.
    
    Args:
        power_metrics: Parsed power metrics from report
        num_additions: Number of addition operations performed in simulation
        num_sum_bits: Number of bits in the sum output (8 for 8-bit adder)
        clock_period_ns: Clock period in nanoseconds
    
    Returns:
        NormalizedMetrics with energy per operation, per bit, etc.
    """
    # Simulation time = num_additions * clock_cycles_per_addition * clock_period
    # Assuming 2 cycles per addition (1 for input register, 1 for output register)
    cycles_per_addition = 2
    total_cycles = num_additions * cycles_per_addition + 10  # +10 for idle cycles
    simulation_time_ns = total_cycles * clock_period_ns
    
    # Total energy in picojoules: E = P * t
    # P in mW, t in ns -> E in pJ
    total_energy_pj = power_metrics.total_power_mw * simulation_time_ns
    clock_energy_pj = power_metrics.clock_power_mw * simulation_time_ns
    logic_energy_pj = power_metrics.logic_power_mw * simulation_time_ns
    leakage_energy_pj = power_metrics.leakage_power_mw * simulation_time_ns
    
    # Energy per addition
    energy_per_addition_pj = total_energy_pj / num_additions if num_additions > 0 else 0
    
    # Energy per sum bit (averaged over all additions)
    total_sum_bits = num_additions * num_sum_bits
    energy_per_sum_bit_pj = total_energy_pj / total_sum_bits if total_sum_bits > 0 else 0
    
    # Estimate input toggles (rough approximation)
    # Each addition involves 2*num_sum_bits input bits + cin + (anc for reversible)
    # Assuming ~50% toggle rate on average
    avg_toggle_rate = 0.5
    bits_per_input = 2 * num_sum_bits + 1  # a + b + cin
    estimated_toggles = num_additions * bits_per_input * avg_toggle_rate
    energy_per_toggle_pj = total_energy_pj / estimated_toggles if estimated_toggles > 0 else 0
    
    # Energy fractions
    total = clock_energy_pj + logic_energy_pj + leakage_energy_pj
    clock_fraction = clock_energy_pj / total if total > 0 else 0
    logic_fraction = logic_energy_pj / total if total > 0 else 0
    leakage_fraction = leakage_energy_pj / total if total > 0 else 0
    
    # Annotation coverage
    if power_metrics.total_pins > 0:
        annotation_coverage = power_metrics.annotated_pins / power_metrics.total_pins
    elif power_metrics.annotated_pins > 0:
        annotation_coverage = 1.0  # Assume all pins annotated if count provided
    else:
        annotation_coverage = 0.0
    
    return NormalizedMetrics(
        energy_per_addition_pj=energy_per_addition_pj,
        energy_per_sum_bit_pj=energy_per_sum_bit_pj,
        energy_per_toggle_pj=energy_per_toggle_pj,
        clock_energy_fraction=clock_fraction,
        logic_energy_fraction=logic_fraction,
        leakage_energy_fraction=leakage_fraction,
        annotation_coverage=annotation_coverage,
    )


def print_metrics(
    power: PowerMetrics,
    normalized: NormalizedMetrics,
    output_format: str = "text"
) -> None:
    """Print metrics in specified format."""
    
    if output_format == "json":
        result = {
            "design_name": power.design_name,
            "power_mw": {
                "total": power.total_power_mw,
                "internal": power.internal_power_mw,
                "switching": power.switching_power_mw,
                "leakage": power.leakage_power_mw,
                "clock": power.clock_power_mw,
                "logic": power.logic_power_mw,
            },
            "normalized_energy_pj": {
                "per_addition": normalized.energy_per_addition_pj,
                "per_sum_bit": normalized.energy_per_sum_bit_pj,
                "per_toggle": normalized.energy_per_toggle_pj,
            },
            "energy_breakdown": {
                "clock_fraction": normalized.clock_energy_fraction,
                "logic_fraction": normalized.logic_energy_fraction,
                "leakage_fraction": normalized.leakage_energy_fraction,
            },
            "annotation_coverage": normalized.annotation_coverage,
        }
        print(json.dumps(result, indent=2))
        
    elif output_format == "csv":
        headers = [
            "design", "total_mw", "internal_mw", "switching_mw", "leakage_mw",
            "clock_mw", "logic_mw", "energy_per_add_pj", "energy_per_bit_pj",
            "energy_per_toggle_pj", "clock_frac", "logic_frac", "leakage_frac",
            "annotation_coverage"
        ]
        values = [
            power.design_name,
            f"{power.total_power_mw:.6f}",
            f"{power.internal_power_mw:.6f}",
            f"{power.switching_power_mw:.6f}",
            f"{power.leakage_power_mw:.6f}",
            f"{power.clock_power_mw:.6f}",
            f"{power.logic_power_mw:.6f}",
            f"{normalized.energy_per_addition_pj:.3f}",
            f"{normalized.energy_per_sum_bit_pj:.3f}",
            f"{normalized.energy_per_toggle_pj:.3f}",
            f"{normalized.clock_energy_fraction:.3f}",
            f"{normalized.logic_energy_fraction:.3f}",
            f"{normalized.leakage_energy_fraction:.3f}",
            f"{normalized.annotation_coverage:.3f}",
        ]
        print(",".join(headers))
        print(",".join(values))
        
    else:  # text format
        print("=" * 60)
        print(f"Power Analysis: {power.design_name}")
        print("=" * 60)
        print()
        print("Power Breakdown (mW):")
        print(f"  Total Power:      {power.total_power_mw:12.6f} mW")
        print(f"  Internal Power:   {power.internal_power_mw:12.6f} mW")
        print(f"  Switching Power:  {power.switching_power_mw:12.6f} mW")
        print(f"  Leakage Power:    {power.leakage_power_mw:12.6f} mW")
        print(f"  Clock Power:      {power.clock_power_mw:12.6f} mW")
        print(f"  Logic Power:      {power.logic_power_mw:12.6f} mW")
        print()
        print("Normalized Energy Metrics:")
        print(f"  Energy per Addition:   {normalized.energy_per_addition_pj:10.3f} pJ")
        print(f"  Energy per Sum Bit:    {normalized.energy_per_sum_bit_pj:10.3f} pJ")
        print(f"  Energy per Toggle:     {normalized.energy_per_toggle_pj:10.3f} pJ")
        print()
        print("Energy Distribution:")
        print(f"  Clock:     {normalized.clock_energy_fraction * 100:6.2f}%")
        print(f"  Logic:     {normalized.logic_energy_fraction * 100:6.2f}%")
        print(f"  Leakage:   {normalized.leakage_energy_fraction * 100:6.2f}%")
        print()
        if normalized.annotation_coverage > 0:
            print(f"Activity Annotation Coverage: {normalized.annotation_coverage * 100:.1f}%")
        else:
            print("WARNING: No activity annotation detected - power may be inaccurate!")
        print()


def compare_designs(
    reports: list[str],
    num_additions: int,
    num_sum_bits: int,
    clock_period_ns: float,
    output_format: str = "text"
) -> None:
    """Compare power metrics across multiple designs."""
    
    results = []
    for report_path in reports:
        power = parse_openroad_power_report(report_path)
        normalized = compute_normalized_metrics(
            power, num_additions, num_sum_bits, clock_period_ns
        )
        results.append((power, normalized))
    
    if output_format == "json":
        comparison = {
            "designs": [
                {
                    "name": p.design_name,
                    "total_power_mw": p.total_power_mw,
                    "energy_per_addition_pj": n.energy_per_addition_pj,
                    "energy_per_sum_bit_pj": n.energy_per_sum_bit_pj,
                    "clock_fraction": n.clock_energy_fraction,
                    "logic_fraction": n.logic_energy_fraction,
                }
                for p, n in results
            ]
        }
        print(json.dumps(comparison, indent=2))
        
    elif output_format == "csv":
        print("design,total_mw,energy_per_add_pj,energy_per_bit_pj,clock_frac,logic_frac")
        for power, normalized in results:
            print(f"{power.design_name},{power.total_power_mw:.6f},"
                  f"{normalized.energy_per_addition_pj:.3f},"
                  f"{normalized.energy_per_sum_bit_pj:.3f},"
                  f"{normalized.clock_energy_fraction:.3f},"
                  f"{normalized.logic_energy_fraction:.3f}")
    else:
        print("=" * 80)
        print("Power Comparison Across Designs")
        print("=" * 80)
        print()
        
        # Find baseline (first non-reversible design for comparison)
        baseline = None
        for power, normalized in results:
            if "reversible" not in power.design_name.lower():
                baseline = (power, normalized)
                break
        if baseline is None and results:
            baseline = results[0]
        
        # Print comparison table
        header = f"{'Design':<25} {'Total (mW)':<12} {'E/Add (pJ)':<12} {'E/Bit (pJ)':<12} {'Clock %':<10} {'Logic %':<10}"
        print(header)
        print("-" * len(header))
        
        for power, normalized in results:
            print(f"{power.design_name:<25} "
                  f"{power.total_power_mw:<12.6f} "
                  f"{normalized.energy_per_addition_pj:<12.3f} "
                  f"{normalized.energy_per_sum_bit_pj:<12.3f} "
                  f"{normalized.clock_energy_fraction * 100:<10.2f} "
                  f"{normalized.logic_energy_fraction * 100:<10.2f}")
        
        print()
        
        # Calculate reversible overhead if applicable
        reversible_result = None
        conv_result = None
        for power, normalized in results:
            if "reversible" in power.design_name.lower():
                reversible_result = (power, normalized)
            elif conv_result is None:
                conv_result = (power, normalized)
        
        if reversible_result and conv_result:
            rev_power, rev_norm = reversible_result
            conv_power, conv_norm = conv_result
            
            print("Reversible Design Overhead Analysis:")
            print("-" * 40)
            
            power_overhead = (rev_power.total_power_mw / conv_power.total_power_mw - 1) * 100
            energy_overhead = (rev_norm.energy_per_addition_pj / conv_norm.energy_per_addition_pj - 1) * 100
            
            print(f"  Power overhead vs {conv_power.design_name}: {power_overhead:+.1f}%")
            print(f"  Energy/add overhead: {energy_overhead:+.1f}%")
            print()
            print("Note: Overhead includes garbage/ancilla signal activity.")
            print("      Use clock gating on garbage outputs to reduce overhead.")
        
        print()


def main():
    parser = argparse.ArgumentParser(
        description="Parse OpenROAD power reports and compute normalized energy metrics",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument(
        "report_files",
        nargs="+",
        help="Power report file(s) to parse"
    )
    parser.add_argument(
        "--num-additions", "-n",
        type=int,
        default=256,
        help="Number of addition operations in simulation (default: 256)"
    )
    parser.add_argument(
        "--num-sum-bits", "-b",
        type=int,
        default=8,
        help="Number of sum bits in adder (default: 8)"
    )
    parser.add_argument(
        "--clock-period", "-c",
        type=float,
        default=25.0,
        help="Clock period in nanoseconds (default: 25)"
    )
    parser.add_argument(
        "--compare",
        action="store_true",
        help="Compare multiple power reports"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON"
    )
    parser.add_argument(
        "--csv",
        action="store_true",
        help="Output results as CSV"
    )
    
    args = parser.parse_args()
    
    # Determine output format
    if args.json:
        output_format = "json"
    elif args.csv:
        output_format = "csv"
    else:
        output_format = "text"
    
    # Validate input files
    for filepath in args.report_files:
        if not Path(filepath).exists():
            print(f"ERROR: File not found: {filepath}", file=sys.stderr)
            sys.exit(1)
    
    if args.compare or len(args.report_files) > 1:
        compare_designs(
            args.report_files,
            args.num_additions,
            args.num_sum_bits,
            args.clock_period,
            output_format
        )
    else:
        # Single file analysis
        power = parse_openroad_power_report(args.report_files[0])
        normalized = compute_normalized_metrics(
            power,
            args.num_additions,
            args.num_sum_bits,
            args.clock_period
        )
        print_metrics(power, normalized, output_format)


if __name__ == "__main__":
    main()
