#!/usr/bin/env python3
"""
parse_power_reports.py

Parses OpenROAD power reports and generates a summary CSV.

This script reads the power report files generated by OpenROAD and extracts
key power metrics, then outputs them to a CSV file for comparison.

Usage:
    python3 scripts/parse_power_reports.py

The script expects power reports in scripts/ directory:
    - reversible_power_report.txt
    - ripple_power_report.txt
    - carry_select_power_report.txt

Output:
    - scripts/power_summary_tt_025C_1v80.csv
"""

import os
import re
import csv
import sys
from pathlib import Path


def parse_power_report(filepath: str) -> dict:
    """
    Parse an OpenROAD power report and extract power metrics.

    Args:
        filepath: Path to the power report file

    Returns:
        Dictionary with power metrics (internal, switching, leakage, total)
    """
    metrics = {
        'internal_power_mw': None,
        'switching_power_mw': None,
        'leakage_power_mw': None,
        'total_power_mw': None,
    }

    if not os.path.exists(filepath):
        print(f"Warning: Report file not found: {filepath}", file=sys.stderr)
        return metrics

    with open(filepath, 'r') as f:
        content = f.read()

    # OpenROAD power report format patterns
    # Example lines:
    #   Internal Power:  1.23e-03 W
    #   Switching Power: 4.56e-04 W
    #   Leakage Power:   7.89e-06 W
    #   Total Power:     1.69e-03 W

    # Pattern for power values in scientific notation or decimal
    power_pattern = r'([\d.]+(?:e[+-]?\d+)?)\s*([munpfW]+)?'

    # Try to find internal power
    match = re.search(r'Internal\s+Power[:\s]+([\d.]+(?:e[+-]?\d+)?)\s*([munpfW]*)', content, re.IGNORECASE)
    if match:
        metrics['internal_power_mw'] = convert_to_mw(match.group(1), match.group(2))

    # Try to find switching power
    match = re.search(r'Switching\s+Power[:\s]+([\d.]+(?:e[+-]?\d+)?)\s*([munpfW]*)', content, re.IGNORECASE)
    if match:
        metrics['switching_power_mw'] = convert_to_mw(match.group(1), match.group(2))

    # Try to find leakage power
    match = re.search(r'Leakage\s+Power[:\s]+([\d.]+(?:e[+-]?\d+)?)\s*([munpfW]*)', content, re.IGNORECASE)
    if match:
        metrics['leakage_power_mw'] = convert_to_mw(match.group(1), match.group(2))

    # Try to find total power
    match = re.search(r'Total\s+Power[:\s]+([\d.]+(?:e[+-]?\d+)?)\s*([munpfW]*)', content, re.IGNORECASE)
    if match:
        metrics['total_power_mw'] = convert_to_mw(match.group(1), match.group(2))

    # Alternative pattern: table format
    # Group     Internal  Switching    Leakage      Total
    #  Design   1.23e-03   4.56e-04   7.89e-06   1.69e-03
    if metrics['total_power_mw'] is None:
        # Try to parse table format
        lines = content.split('\n')
        for i, line in enumerate(lines):
            if 'Total' in line and 'Internal' in line and 'Switching' in line:
                # Found header line, next non-empty line should have values
                for j in range(i + 1, min(i + 5, len(lines))):
                    data_line = lines[j].strip()
                    if data_line and not data_line.startswith('#'):
                        # Parse the data line
                        parts = data_line.split()
                        if len(parts) >= 4:
                            try:
                                # Assuming format: name internal switching leakage total
                                # or just: internal switching leakage total
                                if len(parts) >= 5:
                                    metrics['internal_power_mw'] = convert_to_mw(parts[1], 'W')
                                    metrics['switching_power_mw'] = convert_to_mw(parts[2], 'W')
                                    metrics['leakage_power_mw'] = convert_to_mw(parts[3], 'W')
                                    metrics['total_power_mw'] = convert_to_mw(parts[4], 'W')
                                else:
                                    metrics['internal_power_mw'] = convert_to_mw(parts[0], 'W')
                                    metrics['switching_power_mw'] = convert_to_mw(parts[1], 'W')
                                    metrics['leakage_power_mw'] = convert_to_mw(parts[2], 'W')
                                    metrics['total_power_mw'] = convert_to_mw(parts[3], 'W')
                            except (ValueError, IndexError):
                                pass
                        break

    return metrics


def convert_to_mw(value_str: str, unit: str) -> float:
    """
    Convert a power value to milliwatts.

    Args:
        value_str: Numeric value as string
        unit: Unit string (W, mW, uW, nW, pW, etc.)

    Returns:
        Power value in milliwatts
    """
    try:
        value = float(value_str)
    except ValueError:
        return None

    if unit is None:
        unit = 'W'

    unit = unit.lower().strip()

    # Convert to base watts first, then to mW
    if 'pw' in unit or unit == 'p':
        value *= 1e-12
    elif 'nw' in unit or unit == 'n':
        value *= 1e-9
    elif 'uw' in unit or unit == 'u':
        value *= 1e-6
    elif 'mw' in unit or unit == 'm':
        value *= 1e-3
    elif 'w' in unit:
        pass  # Already in watts
    # Assume watts if no unit

    # Convert to milliwatts
    return value * 1000


def main():
    """Main entry point."""
    # Determine script directory
    script_dir = Path(__file__).parent.resolve()

    # Report files
    reports = {
        'reversible': script_dir / 'reversible_power_report.txt',
        'ripple': script_dir / 'ripple_power_report.txt',
        'carry_select': script_dir / 'carry_select_power_report.txt',
    }

    # Output CSV
    output_csv = script_dir / 'power_summary_tt_025C_1v80.csv'

    print("Parsing power reports...")

    results = []
    for design_name, report_path in reports.items():
        print(f"  Processing: {design_name}")
        metrics = parse_power_report(str(report_path))
        metrics['design'] = design_name
        results.append(metrics)

    # Write CSV
    print(f"\nWriting summary to: {output_csv}")

    fieldnames = ['design', 'internal_power_mw', 'switching_power_mw', 'leakage_power_mw', 'total_power_mw']

    with open(output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in results:
            writer.writerow(row)

    # Print summary table
    print("\nPower Summary (mW):")
    print("-" * 80)
    print(f"{'Design':<15} {'Internal':<15} {'Switching':<15} {'Leakage':<15} {'Total':<15}")
    print("-" * 80)

    for row in results:
        internal = f"{row['internal_power_mw']:.6f}" if row['internal_power_mw'] is not None else "N/A"
        switching = f"{row['switching_power_mw']:.6f}" if row['switching_power_mw'] is not None else "N/A"
        leakage = f"{row['leakage_power_mw']:.6f}" if row['leakage_power_mw'] is not None else "N/A"
        total = f"{row['total_power_mw']:.6f}" if row['total_power_mw'] is not None else "N/A"
        print(f"{row['design']:<15} {internal:<15} {switching:<15} {leakage:<15} {total:<15}")

    print("-" * 80)
    print(f"\nCSV written to: {output_csv}")

    return 0


if __name__ == '__main__':
    sys.exit(main())
